config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  devise_for :cocks, :controllers => {
    :registrations => 'cocks/registrations',
    :sessions => 'cocks/sessions'
  }

  devise_scope :cock do
    get "sign_in", :to => "cocks/sessions#new"
    get "sign_out", :to => "cocks/sessions#destroy"
  end

  resources :foods, expect: :show
  root to: "foods#toppage"
  get "/toppage", to:"foods#toppage"
  resources :users, only: :show
  get "/store/:id", to: "stores#show"
  post "/store/:id", to: "stores#create"
  get "/search", to: "foods#search"
  resources :cocks, only: :show
  resources :comments, only: %i[create destroy]
  resources :orders, only: %i[index create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cock.rb
class Cock < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true, length: {maximum: 1000}
  belongs_to :food
  belongs_to :user
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :stores, dependent: :delete_all
  has_many :users, through: :stores

  has_many :comments, dependent: :delete_all
  has_many :foods, through: :comments

  belongs_to :cock

  mount_uploader :image, ImageUploader
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stores, dependent: :delete_all
  has_many :foods, through: :stores
  
  has_many :comments, dependent: :delete_all
  has_many :foods, through: :comments

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postcode])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:prefecture_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address_city])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address_street])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address_building])
  end

  def set_search
    @search = Food.ransack(params[:q])
    @search_foods = @search.result(distinct: true).order(created_at: "DESC").page(params[:page]).per(3)
  end

end

app/controllers/cocks/unlocks_controller.rb
# frozen_string_literal: true

class Cocks::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/cocks_controller.rb
class CocksController < ApplicationController
  def show
    @foods = Food.where(cock_id: current_cock.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_to "/store/#{comment.food.id}"
    else
      redirect_to :back, flash: {
        comment: comment,
        error_message: comment.errors.full_messages
      }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment_food_id = comment.food.id
    comment.delete
    redirect_to "/store/#{comment_food_id}", flash: {notice: "コメントが削除されました"}
  end

  private

  def comment_params
    params.require(:comment).permit(:food_id, :comment, :user_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    def index
        @foods = Food.page(params[:page])
    end

    def new
        @food = Food.new(flash[:notice])
    end

    def create
        food = Food.new(food_params)
        if food.save
            flash[:notice] = "「#{food.title}」を追加しました"
            redirect_to foods_path
        else
            redirect_to new_food_path, flash: {
                food: food,
                error_messages: food.errors.full_messages
            }
        end
    end

    def show
    end

    def edit
        @food = Food.find(params[:id])
    end

    def update
        @food = Food.find(params[:id])
        @food.update(food_params)
        redirect_to foods_path
    end

    def destroy
        food = Food.find(params[:id])
        food.destroy
        flash[:notice] = "「#{food.title}」を削除しました"
        redirect_to foods_path
    end

    def search
    end

    def toppage
    end

    private
    def food_params
        params.require(:food).permit(:image, :title, :content, :cock_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @stores = Store.where(cock_id: current_cock.id)
  end

  def destroy
    store = Store.find(params[:id])
    store.destroy
    redirect_to orders_path
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @food = Food.find(params[:id])
    @store = Store.new
    @comment = Comment.new(food_id: @food.id)
  end

  def create
    Store.create(user_id: current_user.id,food_id: params[:id],cock_id: params[:store][:cock_id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(current_user.id)
   @stores = Store.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocks_helper.rb
module CocksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="p-comment__list">
  <div class="p-comment__item">
    <p><%= simple_format(comment.comment) %></p>
    <div class="p-comment__bottomLine">
      <span><%= comment.user.name %></span>
      <span><%= comment.created_at.to_s(:datetime_jp) %></span>
      <% if current_user %>
        <% if comment.user_id == current_user.id %>
          <span><%= link_to "削除", comment, method: :delete, data: {confirm: "削除してもよろしいですか"} %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/edit.html.erb
<h1>メニューを編集する</h1>
<%= form_for @food do |f| %>
    <p>
    <%= f.label :image, "画像をアップロード" %>
    <%= f.file_field :image %>
    </p>
    <p>
    <%= f.label :title, "メニューの名前" %><br>
    <%= f.text_field :title%>
    </p>
    <br>
    <p>
    <%= f.label :content, "メニューの説明" %><br>
    <%= f.text_area :content %>
    </p>
    <br>
    <%= f.submit "追加する", class: "btn btn-primary" %>
<% end %>

app/views/foods/index.html.erb
<h1>商品一覧</h1>
<div class="row">
  <% @foods.each do |food| %>
  <div class="col-sm-6 col-md-4">
    <div style="height: 500px;">
      <div class="card">
        <%= image_tag(food.image , :class => "responsive-img ", :height => "250") unless food.image.blank?%>
        <div class="caption container">
          <h4><%= truncate(food.title, length: 15) %></h4>
          <em>コック：<%= food.cock.nickname %></em>
          <p><%= truncate(food.content, length: 60) %></p>
          <p></p>
          <p><% if (cock_signed_in?) and (!user_signed_in?) and (food.cock_id == current_cock.id) %>
               <%= link_to "編集", edit_food_path(food), class: "btn btn-primary" %> <%= link_to "削除", food, class: "btn btn-primary", method: :delete %>
             <% elsif !(cock_signed_in?) %>
               <%= link_to "商品詳細", "/store/#{food.id}", class: "btn btn-primary" %>
             <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="mx-auto" style="width: 200px;">
  <%= paginate @foods %>
</div>

app/views/foods/new.html.erb
<h2>メニューを追加する</h2>
<form>
  <%= form_for @food do |f| %>
    <%= f.hidden_field :cock_id, :value => current_cock.id %>
    <div class="form-group">
      <%= f.label :image, "画像をアップロード" %><br>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label :title, "メニューの名前" %><br>
      <%= f.text_field :title, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :content, "メニューの説明" %><br>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <%= f.submit "追加する", class: "btn btn-primary" %>
  <% end %>
</form>

app/views/foods/search.html.erb
<div class="row">
  <% @search_foods.each do |food| %>
  <div class="col-sm-6 col-md-4">
    <div style="height: 450px;">
      <div class="card">
        <%= image_tag(food.image , :class => "responsive-img", :height => "250") unless food.image.blank?%>
        <div class="caption container">
          <h4><%= truncate(food.title, length: 15) %></h4>
          <em>コック：<%= food.cock.nickname %></em>
          <p><%= truncate(food.content, length: 60) %></p>
          <p></p>
          <p><% if (cock_signed_in?) and (!user_signed_in?) and (food.cock_id == current_cock.id) %>
               <%= link_to "編集", edit_food_path(food), class: "btn btn-primary" %> <%= link_to "削除", food, class: "btn btn-primary", method: :delete %>
             <% elsif !(cock_signed_in?) %>
               <%= link_to "商品詳細", "/store/#{food.id}", class: "btn btn-primary" %>
             <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/foods/toppage.html.erb
<%= stylesheet_link_tag 'toppage' %>

<div>
  <p>
  <% if user_signed_in? %>
    <p>コックとしてアクセスするにはユーザーログアウトをしてください</p>
  <% else %>
    <% if cock_signed_in? %>
      <span class="login-block-left"><%= link_to "コック専用ログアウト", destroy_cock_session_path, method: :delete, class:"btn btn-primary btn-lg" %></span>
      <span class="login-block-right"><%= link_to '商品投稿画面へ', new_food_path, class:"btn btn-primary btn-lg" %></span>
    <% else %>
      <span class="login-block-left"><%= link_to "コック専用ログイン", new_cock_session_path, class: 'post btn btn-primary btn-lg' %></span>
      <span class="login-block-right"><%= link_to "コック専用新規登録", new_cock_registration_path, class: 'post btn btn-primary btn-lg' %></span>
    <% end %>
  <% end %>
</div>

app/views/stores/create.html.erb
<h1>商品の購入が完了しました</h1>
<p>お届けまで少々お待ちください</p>
<%= link_to "マイページ", user_path(current_user.id)  %>

app/views/stores/show.html.erb
<h1>商品詳細ページ</h1>
<%= image_tag(@food.image , :class => "responsive-img", :height => "600") unless @food.image.blank?%>
<h4><%= @food.title %></h4>
<p>コック：<%= @food.cock.nickname %></p>
<h3>商品詳細</h3>
<p><%= @food.content %></p>

<% if user_signed_in? and !(cock_signed_in?) %>
  <%= form_for @store, url: "/store/#{@food.id}", html: {method: :post} do |s| %>
    <%= s.hidden_field :cock_id, :value => @food.cock_id %>
    <%= s.submit "購入する", class: "btn btn-primary" %>
  <% end %>

  <div class="p-comment__formBox">
    <%= form_for @comment do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :food_id %>
      <%= f.hidden_field :cock_id, :value => @food.cock_id %>
      <div class="form-group">
        <%= f.label :comment, 'コメントを記入(投稿すると名前も表示されます)' %>
        <%= f.text_area :comment, class: 'form-control', rows: 4 %>
      </div>
      <%= f.submit '送信', class: 'btn btn-primary' %>
    <% end %>
  </div>
<% elsif !(cock_signed_in?) and !(user_signed_in?) %>
  <p class="font-weight-bold">購入するには、先にユーザーログインまたはユーザー登録を完了してください</p>
<% end %>

<div class="p-comment__list">
  <div class="p-comment_listTitle">コメント</div>
  <%= render @food.comments %>
</div>