config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  devise_for :cocks, :controllers => {
    :registrations => 'cocks/registrations',
    :sessions => 'cocks/sessions'
  }

  devise_scope :cock do
    get "sign_in", :to => "cocks/sessions#new"
    get "sign_out", :to => "cocks/sessions#destroy"
  end

  resources :foods, expect: :show
  root to: "foods#toppage"
  get "/toppage", to:"foods#toppage"
  resources :users, only: :show
  get "/store/:id", to: "stores#show"
  post "/store/:id", to: "stores#create"
  get "/search", to: "foods#search"
  resources :cocks, only: :show
  resources :comments, only: %i[create destroy]
  resources :orders, only: %i[index create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cock.rb
class Cock < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true, length: {maximum: 1000}
  belongs_to :food
  belongs_to :user
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :stores, dependent: :delete_all
  has_many :users, through: :stores

  has_many :comments, dependent: :delete_all
  has_many :foods, through: :comments

  belongs_to :cock

  mount_uploader :image, ImageUploader
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stores, dependent: :delete_all
  has_many :foods, through: :stores
  
  has_many :comments, dependent: :delete_all
  has_many :foods, through: :comments

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/cocks_controller.rb
class CocksController < ApplicationController
  def show
    @foods = Food.where(cock_id: current_cock.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_to "/store/#{comment.food.id}"
    else
      redirect_to :back, flash: {
        comment: comment,
        error_message: comment.errors.full_messages
      }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment_food_id = comment.food.id
    comment.delete
    redirect_to "/store/#{comment_food_id}", flash: {notice: "コメントが削除されました"}
  end

  private

  def comment_params
    params.require(:comment).permit(:food_id, :comment, :user_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    def index
        @foods = Food.page(params[:page])
    end

    def new
        @food = Food.new(flash[:notice])
    end

    def create
        food = Food.new(food_params)
        if food.save
            flash[:notice] = "「#{food.title}」を追加しました"
            redirect_to foods_path
        else
            redirect_to new_food_path, flash: {
                food: food,
                error_messages: food.errors.full_messages
            }
        end
    end

    def show
    end

    def edit
        @food = Food.find(params[:id])
    end

    def update
        @food = Food.find(params[:id])
        @food.update(food_params)
        redirect_to foods_path
    end

    def destroy
        food = Food.find(params[:id])
        food.destroy
        flash[:notice] = "「#{food.title}」を削除しました"
        redirect_to foods_path
    end

    def search
    end

    def toppage
    end

    private
    def food_params
        params.require(:food).permit(:image, :title, :content, :cock_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @stores = Store.where(cock_id: current_cock.id)
  end

  def destroy
    store = Store.find(params[:id])
    store.destroy
    redirect_to orders_path
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @food = Food.find(params[:id])
    @store = Store.new
    @comment = Comment.new(food_id: @food.id)
  end

  def create
    Store.create(user_id: current_user.id,food_id: params[:id],cock_id: params[:store][:cock_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(current_user.id)
   @stores = Store.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocks_helper.rb
module CocksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Health & Muscle Delivery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="/foods">Health & Muscle delivery</a>
            </div>
              <% if cock_signed_in? and !(user_signed_in?) %>
                <%= link_to "コックログアウト", destroy_cock_session_path, method: :delete, class:"navber-link" %>
                <%= link_to "メニューの追加", new_food_path, class:"navber-link" %>
                <%= link_to "コックマイページ", cock_path(current_cock.id), class:"navber-link"  %>
              <% end %>

              <% if user_signed_in? and !(cock_signed_in?) %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"navber-link" %>
                <%= link_to "ユーザーマイページ", user_path(current_user.id), class:"navber-link"  %>
                <%= link_to "コックの方はこちら", "/toppage", class:"navber-link"  %>
              <% elsif !(user_signed_in?) and !(cock_signed_in?) %>
                <%= link_to "ユーザーログイン", new_user_session_path, class: "post navber-link" %>
                <%= link_to "ユーザー新規登録", new_user_registration_path, class: "post navber-link" %>
                <%= link_to "コックの方はこちら", "/toppage", class:"navber-link"  %>
              <% end %>
              <dl class="searchbox">
                <%= search_form_for @search, url: "/search" do |f| %>
                  <dt><%= f.text_field :title_cont ,placeholder: '検索するキーワードを入力' %></dt>
                  <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
                <% end %>
              </dl>
        </div>
      </nav>
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:error_message] %>
        <div class="alert alert-warning">
          <ul>
            <% flash[:error_message].each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>